---

- name: Update repositories cache and install "unzip" package
  apt:
    name: unzip
    update_cache: yes
    state: present

- name: Update repositories cache and install "screen" package
  apt:
    name: screen
    update_cache: yes
    state: present

- name: Download Terraria Server
  get_url:
    url: "{{ download_server_link }}"
    dest: "/opt/terraria-server.zip"
    mode: 0664

- name: Creates work directory
  file:
    path: /opt/terraria
    state: directory

- name: Creates release directory
  file:
    path: /opt/terraria/release
    state: directory

- name: Extract terraria.zip into /opt/terraria
  unarchive:
    src: "/opt/terraria-server.zip"
    dest: "/opt/terraria/release"

- name: delete unused folder 
  shell: "mv -vn /opt/terraria/release/*/* /opt/terraria/ && rm -Rf /opt/terraria/release/* && mv /opt/terraria-server.zip /opt/terraria/release"

- name: Set Owner Work directory
  shell: "chown -R root:root /opt/terraria"
  
- name: Set Permission Server Binary
  file:
    path: /opt/terraria/Linux/TerrariaServer.bin.x86_64
    owner: root
    group: root
    mode: '0755'

- name: Creation Terraria User
  shell: "id -u terraria &>/dev/null || useradd -r -m -d /srv/terraria terraria"

- name: Creation Configuration File
  template:
    src: "serverconfig.txt.j2"
    dest: "/opt/terraria/Linux/serverconfig.txt"
    owner: root
    group: root
    mode: 0664

- name: Configure Systemd Service
  copy: 
    src: files/terraria.service 
    dest: /etc/systemd/system/terraria.service
    owner: root
    group: root
    mode: 0664
    
- name: Configure Terraria script management
  copy:
    src: files/terrariad
    dest: /usr/local/bin/terrariad
    owner: root
    group: root
    mode: 0755

- name: Start Terraria Server
  service: 
    name: terraira
    enabled: yes 
    status: started