---

- name: Update repositories cache and install Requirements packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - unzip
    - screen
    - wget

- name: Download Terraria Server
  shell: "wget {{ download_server_link }} -O /opt/terraria-server.zip"

- name: Creates work directory
  file:
    path: /opt/terraria
    state: directory

- name: Creates release directory
  file:
    path: /opt/terraria/release
    state: directory

- name: Extract terraria.zip into /opt/terraria
  unarchive:
    src: "/opt/terraria-server.zip"
    dest: "/opt/terraria/release"
    remote_src: yes

- name: delete unused folder 
  shell: "mv -vn /opt/terraria/release/*/* /opt/terraria/ && rm -Rf /opt/terraria/release/* && mv /opt/terraria-server.zip /opt/terraria/release"

- name: Set Owner Work directory
  shell: "chown -R root:root /opt/terraria"
  
- name: Set Permission Server Binary
  file:
    path: /opt/terraria/Linux/TerrariaServer.bin.x86_64
    owner: root
    group: root
    mode: '0755'

- name: Creation Terraria User
  shell: "id -u terraria &>/dev/null || useradd -r -m -d /srv/terraria terraria"

- name: Creation Configuration File
  template:
    src: "serverconfig.txt.j2"
    dest: "/opt/terraria/Linux/serverconfig.txt"
    owner: root
    group: root
    mode: 0664

- name: Configure Systemd Service
  copy: 
    src: files/terraria.service 
    dest: /etc/systemd/system/terraria.service
    owner: root
    group: root
    mode: 0664
    
- name: Configure Terraria script management
  copy:
    src: files/terrariad
    dest: /usr/local/bin/terrariad
    owner: root
    group: root
    mode: 0755

- name: Start Terraria Server
  systemd:
    state: started
    name: terraria
    daemon_reload: yes
    enabled: yes